// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/complaints/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/complaints/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/complaints/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/complaints/[id].patch').default>>>>
    }
    '/api/complaints/:id/comments': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/complaints/[id]/comments/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/complaints/[id]/comments/index.post').default>>>>
    }
    '/api/complaints/:id/likes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/complaints/[id]/likes/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/complaints/[id]/likes/index.post').default>>>>
    }
    '/api/complaints/engagement': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/complaints/engagement.get').default>>>>
    }
    '/api/complaints/feed': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/complaints/feed.get').default>>>>
    }
    '/api/complaints': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/complaints/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/complaints/index.post').default>>>>
    }
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health.get').default>>>>
    }
    '/api/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upload.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}