name: Documentation
description: Report missing, incorrect, or unclear documentation.
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Good documentation helps everyone. Let us know what needs improving.

  - type: textarea
    id: description
    attributes:
      label: What needs documenting?
      description: Describe what's missing, incorrect, or unclear.
      placeholder: "The README doesn't mention how to run tests, and the API endpoints aren't documented anywhere."
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested improvement
      description: How would you improve the documentation?
    validations:
      required: false
