// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/12/2026, 3:04:10 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/dee_vyn/monolithic-ralph/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dee_vyn/monolithic-ralph/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dee_vyn/monolithic-ralph/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dee_vyn/monolithic-ralph/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dee_vyn/monolithic-ralph/plugins/**/*.{js,ts,mjs}","/Users/dee_vyn/monolithic-ralph/composables/**/*.{js,ts,mjs}","/Users/dee_vyn/monolithic-ralph/utils/**/*.{js,ts,mjs}","/Users/dee_vyn/monolithic-ralph/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dee_vyn/monolithic-ralph/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/dee_vyn/monolithic-ralph/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/dee_vyn/monolithic-ralph/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;